# Generated by Django 2.2.1 on 2019-05-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('content', models.CharField(max_length=2048)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.DataSource')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.DataDomain')),
            ],
        ),
        migrations.CreateModel(
            name='MarkovChainWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('next_word', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.DataDomain')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.DataDomain')),
            ],
        ),
        migrations.AddField(
            model_name='datadomain',
            name='data_sources',
            field=models.ManyToManyField(to='server.DataSource'),
        ),
    ]
